image: $CI_REGISTRY/f329-tutoriais/docker:latest

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive


build document:
  stage: build
  script:
    - latexmk -pdf main.tex -shell-escape
    - mv main.pdf origin.pdf
  artifacts:
    name: document
    paths:
      - origin.pdf
